### ISSUE TITLE
`AddDebugLogger` doesn't output to Application Output

### ISSUE THREAD

**Issue by jfversluis** [roubachof/MetroLog#1]
As discussed in private!

When adding 

```csharp
builder.Logging
            .AddDebugLogger(_ => {});
```

And then calling a log method of any level, e.g.: `_logger.LogInformation("OnCounterClicked()");`, nothing gets output to the application output.

The sample app works, but probably because we reference the source directly and/or the whole code is then built with the debug configuration.

All other logging targets seem to work fine from what I tried.

**Comment by roubachof** [comment]
eheheh, well DebugTarget uses `Debug.WriteLine` that gets stripped with release compilation of the package.

So in fact you have to use the TraceTarget, I will update the readme accordingly and add code of ms extensions for the trace target.
