### ISSUE TITLE
How to configure MetroLog in Blazor Hybrid

### ISSUE THREAD

**Issue by rich25200** [roubachof/MetroLog#10]
### Discussed in https://github.com/roubachof/MetroLog/discussions/9

<div type='discussions-op-text'>

<sup>Originally posted by **rich25200** November 17, 2022</sup>
Hi,

Could you please tell me how to configure MetroLog in Maui Blazor Hybrid?

I have an error as "BeginScope is not supported on MetroLog"..

Thanks</div>

**Comment by roubachof** [comment]
duplicate of #6
