### ISSUE TITLE
System.NullReferenceException: FileTarget.GetCompressedLogsInternal

### ISSUE THREAD

**Issue by SirJohnK** [roubachof/MetroLog#11]
**Case**: Get Compressed Logs in AppCenter `Crashes.GetErrorAttachments` delegate.

**Bug**:  `_logFolder` is null when `GetCompressedLogsInternal` is called before `EnsureInitialized` is called in `FileTargetBase.WriteAsyncCore`.

**Tested solution proposal**: Add `EnsureInitialized` in `FileTargetBase.GetCompressedLogs`.

```c# 
   public async Task<MemoryStream> GetCompressedLogs()
    {
        using (await _lock.LockAsync().ConfigureAwait(false))
        {
            CloseAllOpenStreamsInternal();
            await EnsureInitialized().ConfigureAwait(false);
            return await GetCompressedLogsInternal().ConfigureAwait(false);
        }
    }
```

**Comment by roubachof** [comment]
Hi there, and thanks for your proposal :)
Is it just a hypothesis or did you verify that it actually fixes the issue?

**Comment by SirJohnK** [comment]
Yes, verified! Running it now in my MAUI app. :) (In an local version of this library)

**Comment by roubachof** [comment]
will merge this in a heartbeat :)
There is also this: https://github.com/roubachof/MetroLog/issues/7 if you want to be able to have custom prompt

**Comment by SirJohnK** [comment]
PR created! (Added #7 with sample layout in sample project and had to fix namespace) :)
