### ISSUE TITLE
Guidance for Maui Blazor

### ISSUE THREAD

**Issue by ghendo** [roubachof/MetroLog#17]
Would I be able to get some guidance on invoking GoToLogsPageCommand in a blazor hybrid app in Maui.
You have
`<Button Text="Show Logs"
                        Grid.Column="1"
                        HorizontalOptions="End"
                        VerticalOptions="Center"
                        Command="{Binding GoToLogsPageCommand}"/>`
So I would need the C# version

**Comment by roubachof** [comment]
Just instantiate a LogController object. It's all in there.
