### ISSUE TITLE
`NotImplementedException` when using `MetroLog.MicrosoftExtensions` in command line program.

### ISSUE THREAD

**Issue by phispi** [roubachof/MetroLog#18]
Thanks for MetroLog! With .net7 in Windows 10 I created this simple command line program:

```csharp
using Microsoft.Extensions.Logging;
using MetroLog.MicrosoftExtensions;

class MetroLogExample
{
    static void Main()
    {
        using var loggerFactory = LoggerFactory.Create(builder =>
        {
            builder.AddTraceLogger(options => { options.MinLevel = LogLevel.Trace; });
        });

        ILogger logger = loggerFactory.CreateLogger<MetroLogExample>();
        logger.LogInformation("I'm done now");
    }
}
```
I'm setting up the logger this way because my logger instance needs to implement the `Microsoft.Extensions.Logging.ILogger` interface.
The program successfully writes "I'm done now" to the Visual Studio Debug output but when leaving the Main() method, a `System.NotImplementedException` is thrown. Relevant logs:

```
1|2023-03-16T12:26:13.2334363+00:00|TRACE|1|New log manager created
2|2023-03-16T12:26:13.2615268+00:00|TRACE|1|CreateLogger MetroLogExample
3|2023-03-16T12:26:13.2686274+00:00|TRACE|1|Created Logger 'MetroLogExample'
4|2023-03-16T12:26:13.2806980+00:00|INFO|1|MetroLogExample|I'm done now
Exception thrown: 'System.NotImplementedException' in MetroLog.Net6.dll
An unhandled exception of type 'System.NotImplementedException' occurred in MetroLog.Net6.dll
The method or operation is not implemented.
```
Is this intended behavior/am I doing something wrong/a bug?

Version of MetroLog.Net6: 2.1.0 (via nuget; Date Published: Monday, January 16, 2023 (1/16/2023))

Thank you very much for looking into this.

**Comment by roubachof** [comment]
have you initialized the LoggerFactory ?
https://github.com/roubachof/MetroLog#standard-configuration

**Comment by phispi** [comment]
Thanks. Well, (after stripping down the program) I only did what is written in the program pasted above. The line  `builder.AddTraceLogger(options => { options.MinLevel = LogLevel.Trace; });` is the (only) configuration - using the `Microsoft extensions configuration`. My understanding of the documentation is that this should be all it needs.

**Comment by roubachof** [comment]
Ms extensions config can only work in case of a generic Host.
Check the ms doc: https://learn.microsoft.com/en-us/dotnet/core/extensions/generic-host

**Comment by phispi** [comment]
Thank you. I was hoping to find time to check whether there is any possibility to use Metrolog in command line programs configured with the MS extensions without a generic host before responding (I'm encouraged by the fact that logging works this way - only at program exit the exception occurs). I will post in case I succeed doing so in the future. Thanks again.
