### ISSUE TITLE
Issue with logging to streaming file while in background on iOS

### ISSUE THREAD

**Issue by nbourgogne** [roubachof/MetroLog#19]
I have a basic Maui iOS geolocation app that also works in the background (all the backgrounding setup is OK).

I'm logging update events every time I get them.
A little while after the app goes into the background, any call to LogInformation results in a Native error. No error if the application is active. That's with either trace, inmemory or streaming.

Not sure what could cause that, but basic Debug.Writeline solves the issue, so it really seems triggered by the use of logging?

**Comment by roubachof** [comment]
Can you monitor your app console with XCode (https://stackoverflow.com/questions/7277804/ios-iphone-ipad-ipodtouch-view-real-time-console-log-terminal), then copy paste the exception happening.
I suspect it is related with closing of the log file handle.

**Comment by roubachof** [comment]
closing for lack of answer.
