### ISSUE TITLE
System.InvalidOperationException: 'Unable to resolve service for type 'MetroLog.ILogger' while attempting to activate 'LoggerIssue.MainPage'.'

### ISSUE THREAD

**Issue by HobDev** [roubachof/MetroLog#2]
I want to start logging in a Maui App. But registring the MetroLog in DI throughs exception. The repro is attached below:

[LoggerIssue.zip](https://github.com/roubachof/MetroLog/files/9224079/LoggerIssue.zip)

**Comment by jfversluis** [comment]
You have to use `ILogger<MainPage>` instead of the regular `ILogger`

**Comment by jfversluis** [comment]
If you use `ILogger<MainPage>` instead of just `ILogger` it does work. Not sure if that's intended.

**Comment by HobDev** [comment]
@jfversluis  thank you, it works after implementing your suggestion. It requires the namespace `using Microsoft.Extensions.Logging;`

**Comment by roubachof** [comment]
The interface `ILogger` exists in 2 different namespaces:

In the Microsoft.Extensions context be sure to be using `Microsoft.Extensions.Logging` and not `MetroLog`.

**Comment by roubachof** [comment]
I'm afraid this piece is handled by Microsoft extensions and MAUI hosting DI.
But can you inject simple interfaces ILogger with ms extensions? I think I only saw generic loggers in examples...
I think all loggers must be categorized?

https://stackoverflow.com/questions/52921966/unable-to-resolve-ilogger-from-microsoft-extensions-logging

**Comment by jfversluis** [comment]
Ah I see! That is... confusing 😄 oh well, at least nothing for you to do here!
