### ISSUE TITLE
What about .NET 7?

### ISSUE THREAD

**Issue by Flaechekueste50** [roubachof/MetroLog#24]
Maybe I've overseen something and it isn't a problem, or I've forgot something, but what about support for .NET 7?

I'd love to use MetroLog in my MAUI project but it is absolutely necessary for my project to be in .NET 7 and for now I couldn't get MetroLog to work.

If it does work in .NET  7 and you have any idea what might be the problem or else I'd love to hear it.

**Comment by roubachof** [comment]
all .net6 projects are compatible with .net7 ones
