### ISSUE TITLE
Add alternative way for shaking to get the log screen?

### ISSUE THREAD

**Issue by jfversluis** [roubachof/MetroLog#5]
I tried picking up my heavy desktop machine and shake it, but nothing came up :(

Does it make sense to implement an easier way for the desktop platforms to also show this screen? Some shortcut key or something?

**Comment by 7702244** [comment]
Just write this in your ViewModel command:

`await Shell.Current.Navigation.PushModalAsync(new MetroLogPage());`

**Comment by roubachof** [comment]
can't answer better than the serial number
