### ISSUE TITLE
Timestamp for StreamingFileLogger uses GMT+0 always

### ISSUE THREAD

**Issue by kmt-solution** [roubachof/MetroLog#7]
Would be great if this can be configurable in the _options_, or if it takes the system's time directly.
If this is already implemented, please let me know what I am missing. I am currently on v2.0.1.

<PackageReference Include="MetroLog.Maui" Version="2.0.1" />

**Comment by roubachof** [comment]
In logger option, we should be able to add a property of type Layout, 
Then you could write your own custom `Layout`, and assign it to this property.
By default it would be `SingleLineLayout`.

And then you could do ([reference](https://github.com/roubachof/MetroLog/blob/main/MetroLog.Net6/MicrosoftExtensions/ConsoleLoggerProvider.cs));

```csharp
public ConsoleLoggerProvider(IOptions<LoggerOptions> options)
        : base(new ConsoleTarget(options.Layout), options.Value)
  {
  }
```

It won't be such a big refactoring.
You want to give it a go :) ?
